---
# Liste des partages : un SMB + un export NFS seront créés automatiquement
share_manager_shares: []

# Options NFS imposées
share_manager_nfs_default_options: "10.0.0.0/20(rw,no_subtree_check,anongid=513,async,anonuid=11001)"

# Répertoire pour fichiers SMB
share_manager_smb_shares_dir: /etc/samba/shares.d

# Chemin du shares.conf
share_manager_smb_main_config: /etc/samba/shares.conf

# Groupe ACL supplémentaire par défaut
share_manager_share_default_extra_group: "media"
share_manager_share_default_extra_permissions: "rwx"

share_manager_share_enforce_umask: true
share_manager_share_umask_value: "0002"

share_manager_share_enforce_setgid: true
