---
- name: Ensure NFS Export Exists
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ item.path }} {{ nfs_default_options }}"
    state: present
  loop: "{{ shares_normalized }}"
  notify: Restart NFS
