---
- name: Set setgid bit on shared directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "u=rwx,g=rwxs,o=rx"
    state: directory
  loop: "{{ share_manager_shares_normalized }}"
  when: share_manager_share_enforce_setgid
